'use client'; 

import './globals.css'
import Navbar from "../components/Navbar"
import {SessionProvider} from "next-auth/react"; 
import { CartProvider } from "use-shopping-cart"; 
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <CartProvider shouldPersist={true}>
                  
                             
      <SessionProvider>

      <Navbar />
      {children}
      </SessionProvider>
      </CartProvider> 
      </body>
    </html>
  )
}
